### ISSUE TITLE
do not support boxchart

### ISSUE THREAD

**Issue by Achuan-2** [raacampbell/sigstar#11]
![Clip_2024-07-14_19-05-11](https://github.com/user-attachments/assets/fbc6fb9a-b348-4f15-88a0-cef131360334)

**Comment by raacampbell** [comment]
Should be fixed: 33a2fcf960ef005364981f57d4b90c63603c47b1

In future, please copy and paste code as text rather than as an image.

**Comment by Achuan-2** [comment]
thanks a lot
