### ISSUE TITLE
Give user option to disable sig lines when p is n.s.

### ISSUE THREAD

**Issue by shadowfox87** [raacampbell/sigstar#5]
Hi,

I was wondering how I can simply disable the drawing of the comparison lines when the p-value is not significant? I changed 'n.s.' to ''. I just don't want bars when the p-value is >0.05.

if (p>0.05)
return
end

Something like the above is what I need. I tried to insert this in the makeSignificanceBar() function but it seems that it needs to be inserted before the call to makeSignificanceBar() in the for loop. I did this, but ended up getting an error. 

Any suggestions?

**Comment by raacampbell** [comment]
I don't follow why this is needed. It seems to me you either want to show a pair of groups is non-significant and so you add the comparison line and state "n.s." with the NaN option. Or you don't provide any of this information, in which case you don't feed that comparison into `sigStar` at all.

**Comment by shadowfox87** [comment]
Thanks. That's what I ended up doing. I just had to assign NaN to non-significant values in the groups and stats and then remove those NaNs, so when I make the call to sigStar, I'm not providing the information to draw those lines.
