### ISSUE TITLE
Adjust vertical offset of comparison lines to the data

### ISSUE THREAD

**Issue by shadowfox87** [raacampbell/sigstar#7]
Currently, the spacing between comparison lines is 0.05*myRange(ylim). However, when there is comparisons within the same group, a value in that group may have a standard deviation bar that's high and this can sometimes overlap with the p-value comparison lines. 

An example of what I mean by this is shown here: https://imgur.com/KmDEaca

**Comment by raacampbell** [comment]
Related to #6, which is also a problem with box plots. In that case, however, nothing renders at all.

**Comment by shadowfox87** [comment]
I have fixed the issue! I'll fork and submit it. It was a very minor thing in findMinY() function. The x that is being sent has to use a wider range to ensure that the correct max(YLim) is being used.

**Comment by raacampbell** [comment]
Thanks!
